web:
  build: .
  command: /bin/sh -c "sh script/start.sh"
  volumes:
    - .:/pessoaApp
  volumes_from:
    - bundle
  ports:
    - "8000:3000"
  links:
    - db

bundle:
  image: rails_web
  volumes:
    - /bundle

db:
  image: postgres
